import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'src/shared/ui/components/chadcn/ui/sonner';
import { ReactQueryProvider } from 'src/shared/utils/query-client-provider/query-client.provider';
import { AuthProvider } from 'src/shared/utils/supabase/session.context';
import { ThemeProvider } from 'src/shared/utils/theme-provider/theme-provider';
import './globals.css';
import NavigationBar from './ui/NavigationBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={(inter.className, 'dark')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <AuthProvider>
              <NavigationBar />
              {children}
              <Toaster />
            </AuthProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
